application: combo-combat
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "4d 5h"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /WebPlayer
  static_dir: WebPlayer

- url: /
  static_files: index.html
  upload: index.html


- url: .*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest